# Generated by Django 5.1.6 on 2025-03-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='basket',
            managers=[
            ],
        ),
    ]
